# for running
# java -cp lib/mysql-connector-java-5.1.34-bin.jar:bin admin

all:
	/usr/local/java/bin/javac -d bin -classpath lib/mysql-connector-java-5.1.34-bin.jar src/user.java

clean:
	-@rm bin/admin.class
