# for running
# java -cp lib/mysql-connector-java-5.1.34-bin.jar:bin user

all:
	/usr/local/java1.6/bin/javac -d bin -classpath lib/mysql-connector-java-5.1.34-bin.jar src/user.java

clean:
	-@rm bin/user.class
